### ISSUE TITLE
.edat mods for Dissidia Duodecim don't work (maybe not detected?)

### ISSUE THREAD

**Issue by masterrite** [LiEnby/NoPspEmuDrm#10]
Hi! I'm wondering if you can make NoPspEmuDrm compatible with edat mods for Dissidia? These basically works like DLCs but I'm guessing they don't have license, so NoPspEmuDrm can't detect them. I'm attaching a file for reference. Each mod is made up of 5-7 edat files. If they're successfully installed to the game, you should be able to see the modded model in "Collection" -> "museum" -> character files -> view character and switch with L or R.

Thanks!
[[Lightning][DLC6][2B].zip](https://github.com/LiEnby/NoPspEmuDrm/files/12076134/Lightning.DLC6.2B.zip)

**Comment by LiEnby** [comment]
these DLC files aren't valid EDAT files there missing the EDAT header and stuff, it likely is patching the edat decryption to just read this directly .. it might be possible to 'sign' these edat files though so that unmodified psp fw would accept it

**Comment by masterrite** [comment]
>  it might be possible to 'sign' these edat files though so that unmodified psp fw would accept it

Is it possible to do with NoPspEmuDrm? Would be cool to have mods in official FW
