### ISSUE TITLE
MGS: PW crashes on startup

### ISSUE THREAD

**Issue by ktheticdev** [LiEnby/NoPspEmuDrm#11]
Pretty much what the title says, no errors, nothing unusual, the game simply exits to the main menu when started.

**Comment by ktheticdev** [comment]
Also worth noting that MGS1 (USA) crashes with E-fffffff error.

**Comment by ktheticdev** [comment]
smh fixed by reinstalling the plugin

**Comment by LiEnby** [comment]
maybe you had the kernel plugin installed but the user one not installed correctly, that would have e-FFFFF error ..
