### ISSUE TITLE
Game doesn't launch.

### ISSUE THREAD

**Issue by gilgilgan** [LiEnby/NoPspEmuDrm#12]
Bubble creation was successful. But when I run it, it brings me right back to the home screen.

I have installed several PSP games from version 0.57 of PKGJ, all with the same result.
I was able to read the manual of the installed game.

I've tested with the majority of plugins removed and got the same result.

PSN is logged in, but the device is not authenticated, and version 3.65 and enso ex 5.0 are in use.

My config.txt is:
```

# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/EmergencyMount.skprx
ur0:tai/CpuAffinityChanger.skprx
ur0:tai/ioplus.skprx
ur0:tai/0syscall6.skprx
ur0:tai/nonpdrm_un.skprx
ur0:tai/nopsmdrm.skprx
ur0:tai/NoPspEmuDrm_kern.skprx
ur0:tai/repatch.skprx
ur0:tai/PSVshell.skprx
ur0:tai/reVita.skprx
ur0:tai/cidSpoof.skprx
ur0:tai/mac_address_spoofer.skprx
ur0:tai/itls.skprx
#ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/adrenaline_kernel.skprx
ur0:tai/pspemu-colour-crunch.skprx
ur0:tai/kubridge.skprx
ur0:tai/music_premium.skprx
ur0:tai/Crash-Dump-Save-Disable.skprx

*main
ur0:tai/shellbat.suprx
ur0:tai/nolockscreen_v2.suprx
ur0:tai/download_enabler.suprx
ur0:tai/LowMemMode.suprx
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
ur0:tai/quickmenuplus.suprx
ur0:tai/jav.suprx
ur0:tai/moonshine.suprx
ur0:tai/quietshot.suprx
ur0:tai/pngshot.suprx
ur0:tai/reVitaMotion.suprx
ur0:tai/USBDisable.suprx

*ALL
ur0:tai/NoPspEmuDrm_user.suprx

*NPXS10095
ur0:tai/quietshot.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
#ur0:tai/yamt.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
#ur0:tai/yamt.suprx
*NPXS10036
ur0:tai/reScreeny.suprx
*NPXS10083
ur0:tai/UserAgentSpoofer.suprx
*NPXS10084
ur0:tai/UserAgentSpoofer.suprx

```

**Comment by LiEnby** [comment]
What game doesn't launch ?

**Comment by gilgilgan** [comment]
I've found the cause.
It doesn't work because I haven't registered the device with system activation.

I confirmed this worked and immediately turned off activation and changed the cid to cidspoof.

It would be nice if nopspemudrm could work without system activation like nonpdrm.

**Comment by LiEnby** [comment]
> It would be nice if nopspemudrm could work without system activation like nonpdrm.

it does though .. ?  however if your using a ConsoleID spoofer that could very easily be your problem;

https://github.com/LiEnby/NoPspEmuDrm/blob/master/user/PspNpDrm.c#L76C13-L76C13 
as ConsoleID is used for decryption of PSP license files.

**Comment by gilgilgan** [comment]
Only if the plugin doesn't find tm0:/npdrm/act.dat, can't it refer to some other predefined location (e.g. ur0:/tai/act.dat)?

Then it seems that you can make the plugin work with a backup copy of act.dat regardless of actual activation.(I'm sorry if this is a stupid suggestion, as it's just a non-expert's estimate.)

**Comment by LiEnby** [comment]
>Only if the plugin doesn't find tm0:/npdrm/act.dat, can't it refer to some other predefined location (e.g. ur0:/tai/act.dat)? 

no it determines if the console is activated using ``sceNpDrmCheckActData``, which actually parses the activation file and will give an error if its not activated.

**Comment by LiEnby** [comment]
> > It would be nice if nopspemudrm could work without system activation like nonpdrm.
> 
> it does though .. ? however if your using a ConsoleID spoofer that could very easily be your problem;
> 
> https://github.com/LiEnby/NoPspEmuDrm/blob/main/user/PspNpDrm.c#L76C13-L76C13 as ConsoleID is used for decryption of PSP license files.

try disabling cidspoofer and clearing all the nopspemudrm license files from ux0:/pspemu/PSP/LICENSE

**Comment by LiEnby** [comment]
does it work with v1.05 i just released ? i changed it to read the console id from the idstorage instead..

**Comment by LiEnby** [comment]
i changed it so it reads the console id from idstorage directly, this should get the real console id before CIDSpoofer touches it. try the new version i just put out
