### ISSUE TITLE
E-FFFFFF error on launch

### ISSUE THREAD

**Issue by nonameVHSM** [LiEnby/NoPspEmuDrm#14]
When I try to open any game I get this error, the plugin files are on ur0:/tai/ and I put the two necessary lines on config.txt, I used the vitashell fork in the readme to promote the games  to the live area.

I saw this error referenced here https://github.com/LiEnby/NoPspEmuDrm/issues/11#issuecomment-1666381957 but I'm not sure how I could've installed the user one incorrectly, unless there's something I need to do besides adding ur0:/tai/NoPspEmuDrm_user.suprx under *main

The games open fine on adrenaline

```# ITLS
*KERNEL
ur0:tai/itls.skprx

# YAMT
*NPXS10015
ur0:tai/yamt.suprx
*KERNEL
ur0:tai/yamt_helper.skprx

# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
ur0:tai/0syscall6.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/repatch.skprx
ur0:tai/PSVshell.skprx
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx

# Optional QoL plugins
*KERNEL
# removes brightness and wifi restrictions for games
ur0:tai/NoPowerLimits.skprx
# increases max/decreases min brightness, disabled by default
ur0:tai/vitabright.skprx
ur0:tai/ioplus.skprx
ur0:tai/reVita.skprx
ur0:tai/NoPspEmuDrm_kern.skprx
ur0:tai/kubridge.skprx
*main
# shows battery percentage near the gauge
ur0:tai/shellbat.suprx
# screenshots are png instead of jpg
ur0:tai/pngshot.suprx
ur0:tai/download_enabler.suprx
ur0:tai/reVitaMotion.suprx
ur0:tai/NoPspEmuDrm_user.suprx
```

**Comment by LiEnby** [comment]
This config.txt is incorrect

NoPspEmuDrm needs to be under *ALL not *main (because it's the only way to effect every instance of pspemu)

Like so:

```
*ALL
ur0:/tai/NoPspEmuDrm_user.suprx 
```

**Comment by nonameVHSM** [comment]
> This config.txt is incorrect
> 
> NoPspEmuDrm needs to be under *ALL not *main (because it's the only way to load in every instance of pspemu)
> 
> Like so:
> 
> ```
> *ALL
> ur0:tai/NoPspEmuDrm_user.suprx 
> ```

Thank you so much. I must have dyslexia or something because I actually went through the readme and issues to see if the problem was this and somehow convinced myself that it really was supposed to be put it under *main ugh
