### ISSUE TITLE
PSP Game immediately quits

### ISSUE THREAD

**Issue by piregg** [LiEnby/NoPspEmuDrm#15]
Hi there, I have updated PKGJ to the latest and upgraded a few other things, including trying to get PSP games using your new method. The install appears to have gone ok (GTA ChinaTown Wars), and a bubble appeared, when I tap the bubble it immediately exits.
I double checked the plugins (NoPspEmuDrm_user.suprx and NoPspEmuDrm_kern.skprx) and I can see the files in the correct place (ur0:tai/)

Here is my config that lives ur0:/tai/config.txt

> *main
> ux0:data/vitadb/vdb_daemon.suprx
> ur0:tai/henkaku.suprx
> ur0:tai/shellbat.suprx
> ur0:tai/pngshot.suprx
> ur0:tai/download_enabler.suprx
> # YAMT
> *NPXS10015
> ur0:tai/yamt.suprx
> ur0:tai/henkaku.suprx
> *KERNEL
> ur0:tai/nonpdrm.skprx
> ur0:tai/NoPspEmuDrm_kern.skprx
> ur0:tai/yamt_helper.skprx
> ur0:tai/psvshell.skprx
> ux0:app/pspemucfw/sce_module/adrenaline_kernel.skprx
> ur0:tai/kubridge.skprx
> ur0:tai/fd_fix.skprx
> ur0:tai/nopsmdrm.skprx
> 
> # For users plugins, you must refresh taiHEN from HENkaku Settings for
> # changes to take place.
> # For kernel plugins, you must reboot for changes to take place.
> 
> *NPXS10016
> ur0:tai/henkaku.suprx
> *ALL
> ur0:tai/NoPspEmuDrm_user.suprx

Any help would be appreciated!

**Comment by LiEnby** [comment]
i cannot find (GTA ChinaTown Wars) in PKGJ..

**Comment by LiEnby** [comment]
trying the GTA ChinaTown game myself it does seem to run fine.. hmm

**Comment by piregg** [comment]
Ok thanks for checking. I ran another game and it did infact work, so this lead me to believe something was cached or wrong with this particular game on my system. I looked up the ID and found some folders relating to this game in ux0:/app and appmeta. Not sure what these are for exactly but I deleted the folders for this game, relaunched the game and it now works!
I think the issue is because I had launched several psp games with adrenaline which had created this data, before switching to your method. I'm not sure if there is a way to clear up all this data in advance? 
Thanks again for checking.

**Comment by LiEnby** [comment]
ux0:/app is for VITA games- it shouldnt be used by the pspemu at all; 
appmeta is cache of images / where livearea updates are stored, mostly irrelevant to the pspemu too; as the livearea for these will never be updated;

i dont even know if ux0:/appmeta is supposed to store pspemu stuff. 

the only thing nopspemudrm really caches is the license files it generates; so that it can load up faster next time around ..
