### ISSUE TITLE
Digimon Adventure [ULJS00541] fan translation boots using other methods but not sign_np + NoPspEmuDrm

### ISSUE THREAD

**Issue by 0ver-flow** [LiEnby/NoPspEmuDrm#17]
After leaving a [couple](https://github.com/LiEnby/NoPspEmuDrm/issues/8#issuecomment-1811740848) [comments](https://github.com/LiEnby/NoPspEmuDrm/issues/16) I did some experimenting. I was able to sign the EBOOT.BIN for my translated copy of Digimon Adventure, repack it, and get it to play fully in PPSSPP with no issues. Following this, I tried both sign_np and ChovySign to get the game onto the Vita and running with NoPspEmuDrm.

Both methods for ChovySign (CMA and PSP format copy) worked. Cool. However, sign_np seems to have an issue where it sees the save data as corrupted. When selecting New File, the screen goes completely white. Sometimes it freezes the system. Sometimes it crashes with an error (C1-2858-3). Sometimes it just waits until I press the PS button.

The other thing to note is it boots in Adrenaline (as previously noted, in conjunction with NpDrm_Free) and plays just fine with the sign_np version.

**Comment by LiEnby** [comment]
wait is issues with sign_np actually valid for chovy-sign2? 
what content id are you using for sign_np and what versionkey are you using for sign_np..

**Comment by 0ver-flow** [comment]
Content ID is UP4090-NPUH10091_00-POOLHALLPRODLGPS, version key is E646049058F17F1A8EA6E071868C4C1A. Same goes for UP2006-NPUH10027_00-UNOPSPGAMELOFT09, version key 01A06FCA4B311B0C68C881A763EB6610.

I was just noting how it works using ChovySign without NoPspEmuDrm or Adrenaline, and sign_np with Adrenaline, but not for sign_np with NoPspEmuDrm.

**Comment by LiEnby** [comment]
this is probably an issue with sign_np than anything else. it definitely is not related to NoPspEmuDrm ..
