### ISSUE TITLE
Can't use DLC content with Motorstorm: Arctic Edge

### ISSUE THREAD

**Issue by mrfiskare** [LiEnby/NoPspEmuDrm#21]
Motorstorm: Arctic Edge has a [Collector's Edition DLC](https://motorstorm.fandom.com/f/p/3462884810031643378) that unlocks additional contents in the main game.

This DLC (`UCES01250`) has to be installed into the `PSP/GAME` folder.

The problem is that the `PSP/GAME/UCES01250` folder is already used by the game itself. I have tried placing the content of the DLC in question, alongside with the game files, however this did not trigger the DLC content to be enabled.

**Comment by LiEnby** [comment]
![image](https://github.com/LiEnby/NoPspEmuDrm/assets/39113159/f699f612-e17f-417c-b174-03d80616d1d6)
this is not a valid EDAT file .

**Comment by mrfiskare** [comment]
Interesting, the DLC itself works when paired with an ISO file.

**Comment by LiEnby** [comment]
it is likely they provided the decrypted EDAT file which the stock PSP firmware cannot read,

**Comment by mrfiskare** [comment]
> it is likely they provided the decrypted EDAT file which the stock PSP firmware cannot read,

Okay, so I did some research and found the origins of this DLC within [NPS](https://nopaystation.com)'s database:

| Field           | Value                                                                                           |
|-----------------|-------------------------------------------------------------------------------------------------|
| pkg_Title_ID    | UCES01250                                                                                       |
| Region          | EU                                                                                              |
| Title_and_ID2   | [PSP DLC] MotorStorm®: Arctic Edge Collectors Edition Key [ID: MSAESPECEDKEY001]               |
| pkg_link        | [Download Link](http://zeus.dl.playstation.net/cdn/EP9000/UCES01250_00/FHFFoObJHxaP8e7dFdT4IOnFjQ6nNayliEq3dtn3Bmd90XKRuLKvacugkLqWcW9D8rBS5kyrFkt2uEgD5eIxDbJQTSeBELYGsu8XN.pkg) |
| pkg_Content_ID  | EP9000-UCES01250_00-MSAESPECEDKEY001                                                           |
| pkg_File_Size   | 1226240                                                                                         |
| Date Added      | 2020/01/01                                                                                      |
| VERSION         | 01.00                                                                                           |

*source: https://raw.githubusercontent.com/1jtp8sobiu/NPS_JP/master/rearrange/PSP_AC.tsv*

But the problem still occurs. When you intall the game in eboot format it will be placed into `PSP/GAME/UCES01250`. However the DLC needs to be placed into the same folder, and it has its own PBP file. 

There are no conflicting file names between the two instances, but the game will ignore the DLC content if you merge the two folders together.

The DLC does work however when the game is install in ISO format. (and the DLC is in `PSP/GAME/UCES01250`)

A possible solution could be using the [game categories plugin](https://www.pspunk.com/game-categories-lite), and placing the game and the DLC directories into different locations, but I haven't tried that.

**Comment by LiEnby** [comment]
when using PKG2ZIP to extract this PKG file, use the ``-p`` argument.
![image](https://github.com/LiEnby/NoPspEmuDrm/assets/39113159/87ce7701-27e1-4e9e-81fe-1757984a9c9f)
this gives you the original EDAT file.

**Comment by mrfiskare** [comment]
I actually used this flag to get the eboot format of the game. The DLC got downloaded into this format by default.

Is it possible to merge the two outcomes somehow?

**Comment by LiEnby** [comment]
How would i know if the DLC was working or not? with the encrypted EDAT in there it seems to create a RIF for it atleast suggesting it is attempting to read it.

**Comment by mrfiskare** [comment]
Well, I just told you 3 times that it works, but nevermind (besides, its very easy to try). 

But, I guess the real solution is not using NoPspEmuDrm.

**Comment by mrfiskare** [comment]
> With the encrypted EDAT in there it seems to create a RIF for it seems to work ... ![2024-03-17-100433](https://private-user-images.githubusercontent.com/39113159/313433129-eb93161a-7518-4d36-ae9e-6f4735523034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Mjc3MDEsIm5iZiI6MTcxMDYyNzQwMSwicGF0aCI6Ii8zOTExMzE1OS8zMTM0MzMxMjktZWI5MzE2MWEtNzUxOC00ZDM2LWFlOWUtNmY0NzM1NTIzMDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDIyMTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYjVmMzhkNTU3NGZkZTU1MGNiYmEyZTJiZTczNTE3NGY2M2IwNDdlMmJkYmMxODBiMzczNGJlODAyYTJlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Y6_sD71J_NgTa-mpC_BMIj4R0hRBskciwtYDiNBfKE) this is w EDAT file renamed .. ![2024-03-17-100328](https://private-user-images.githubusercontent.com/39113159/313433148-06ca1784-ff46-4779-8170-953b51c4f798.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Mjc3MDEsIm5iZiI6MTcxMDYyNzQwMSwicGF0aCI6Ii8zOTExMzE1OS8zMTM0MzMxNDgtMDZjYTE3ODQtZmY0Ni00Nzc5LTgxNzAtOTUzYjUxYzRmNzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDIyMTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YWU5YTQ0NmJkNjE3NWJmYjU0NWRmZjNiOGRjYzNkM2E2OGQxOTBlZGZkYjJhY2YxNTJhY2FlNzE1YzI2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tEuNfuOk_CTZonBda2BP9K6ZsImYpaIQTVOqOPzR_EM)

Thx, by the way I didn't know that the PBP file is not needed from the DLC
