### ISSUE TITLE
Is there a way to uninstall the LiveArea bubble without deleting the game?

### ISSUE THREAD

**Issue by Axce** [LiEnby/NoPspEmuDrm#22]
Basically the title: Most of the time I'm happy with NoPspEmuDrm instead of Adrenaline, but for some games I prefer to use Adrenaline for some features (PS1 scaling mostly). For those, is it possible to delete the bubble while keeping the game files, or to install via PKGj without a bubble like the old way?

For now I just install those specific games by copying files into /pspemu, but I'm curious.

Many thanks for your work!

**Comment by LiEnby** [comment]
i suppose you could just rename the pspemu/PSP/GAME folder, delete the bubble, then rename it back.. generally- the vita does not support deleting a bubble without deleting the underlying files for the game, (except on gamecarts) .

**Comment by Axce** [comment]
Thanks I will try that!

**Comment by LiEnby** [comment]
also- you can still install the old way with PKGj either by just not having nopsmdrm, or with a config option that forget exactly what is.
