### ISSUE TITLE
EBOOT.PBP With no _sce_ebbotpbp

### ISSUE THREAD

**Issue by ritchieg9** [LiEnby/NoPspEmuDrm#23]
Hello,
I'm able to install fro PKGj with no issues, but I wonder, how can I manually set a game if the only file I have is the .PBP file?
Thanks

**Comment by LiEnby** [comment]
you would use chovy-gen .. https://github.com/dots-tb/chovy-gen to create __sce_ebootpbp


or,.. it would be generated automatically if you used this [vitashell fork](https://github.com/LiEnby/VitaShell) and did "refresh livearea"  ...
