### ISSUE TITLE
Stuck on PS logo after reboot

### ISSUE THREAD

**Issue by mikhaelcool7** [LiEnby/NoPspEmuDrm#24]
After I copied over the files to ur0:/tai and edited the config.txt, my PSVita no longer boots into the Livearea. Stuck on the PS logo.

**Comment by LiEnby** [comment]
if you hold L at bootup you can disable all plugins, then load vitashell and remove it from your config, 

but im not sure why exactly its not working though

**Comment by mikhaelcool7** [comment]
> if you hold L at bootup you can disable all plugins, then load vitashell and remove it from your config,
> 
> but im not sure why exactly its not working though

Yup I did that after panicking for a while and removed the text from the config.txt. The PSVita works just as it did before now

**Comment by LiEnby** [comment]
can i ask what firmware your on, and like what other plugins you have, its very weird.

**Comment by mikhaelcool7** [comment]
> can i ask what firmware your on, and like what other plugins you have, its very weird.

I think it's on 3.65 but spoofed to the latest version. I followed the Vita Hacks Guide maybe a year ago and it pre-installed a few plugins as I followed the guide. I can share the config.txt here

**Comment by LiEnby** [comment]
yeah give config.txt, its also possible you entered it into the config wrong(?) i dont know??

**Comment by mikhaelcool7** [comment]
> yeah give config.txt, its also possible you entered it into the config wrong(?) i dont know??

[config.txt](https://github.com/user-attachments/files/16920245/config.txt)
I have disabled a few plugins with a hashtag

**Comment by LiEnby** [comment]
hm yeah none of this should be a problem ...

**Comment by LiEnby** [comment]
actually, a stuck PS Logo is usually a sign the vita is creating a coredump, a broken plugin would usually kpanic the vita.
if you look in bootconfig.txt theres a line under like if BSOD_REBOOT or whatever, where it loads coredump.skprx.
and this just takes ages to finish .. uh

**Comment by mikhaelcool7** [comment]
I used the plugin on my PSTV that I recently got, and everything is working just fine and the games that have updates like Socom 3 and LittleBigPlanet update just fine too. Maybe I mistyped something at the time on my PSVita.
