### ISSUE TITLE
PocketStation Save doesn't copy to Memory Card

### ISSUE THREAD

**Issue by gledson999** [LiEnby/NoPspEmuDrm#3]
Hello, I don't know if this is the right place to report this issue, but I noticed that there is a problem related to PocketStation saves (MCX.BIN) in which saves cannot be copied from PocketStation to the memory card through the save manager from PSOne Classic BIOS of PS Vita

Analyzing the save, I noticed that the MCX.BIN is encrypted, but the *.VMP saves do not have encryption, maybe it has some relation?

I found some issue here too related: [https://gamefaqs.gamespot.com/boards/620272-playstation-vita/69252364](url)

**Comment by LiEnby** [comment]
Yes this is a limitation sony put in the vita firmware it cannot be copied from VMP to MCX. 

as well as that content manager will skip copying MCX.BIN . when you backup a PSX save (though i think it can write .)  VMP saves are not encrypted but they are "signed" with an HMAC based signature 

and yes MCX is aes-128-cbc encrypted w this key: 
https://www.psdevwiki.com/vita/Keys#MCX.BIN_key 

as well as that awhile ago i added mcx.bin support to memcardrex 
https://github.com/ShendoXT/memcardrex
