### ISSUE TITLE
PSP game not working...

### ISSUE THREAD

**Issue by chronoss09** [LiEnby/NoPspEmuDrm#5]
Hi

I tested a latest plugin with your fork of Vitashell but it don't work...

**Comment by LiEnby** [comment]
Which game? Didnt work how? ?

**Comment by chronoss09** [comment]
Last day, i tested many PSP/PSX game downloaded with NPS_Browser and it work work very well with your Vitashell fork but yesterday, it don't work. i don't know why and with the last plugin u shared, it give samething... no game on livearea after i actualize into Vitashell...

**Comment by LiEnby** [comment]
but i didnt even change the kernel plugin how could it have possibly broken anything in vitashell :?

**Comment by LiEnby** [comment]
https://github.com/blastrock/pkgj/releases/tag/v0.56-beta3 do you have same issue trying to use this build of pkgj?

**Comment by chronoss09** [comment]
I nevers use pkgi, i download all my game with NPS_Browser and at your first release, all game work fine...

**Comment by LiEnby** [comment]
just tried it on latest version and its working fine? i cant replicate your issue.  please tell me what game exactly you are having this problem with

**Comment by chronoss09** [comment]
Just test with the old plugin and lastest Vitashell fork, it work... with last plugin too it work... don't know why yesterday it don't work... so sorry :(

can this work with some psp plugin like GE Patch or [RemasteredControls](https://github.com/TheOfficialFloW/RemasteredControls) to use the second joystick for camera control ?

**Comment by LiEnby** [comment]
> can this work with some psp plugin like GE Patch or [RemasteredControls](https://github.com/TheOfficialFloW/RemasteredControls) to use the second joystick for camera control ?
Dunno does it work on offically owned psp games ? 
If it requires like an eCFW then it wont work.

> And it's possible to customize the official eboot.pbp ?
what you mean? Change icon or smth? Yeah should be able too

**Comment by chronoss09** [comment]
> Dunno does it work on offically owned psp games ?
> If it requires like an eCFW then it wont work.

Ok i see



> what you mean? Change icon or smth? Yeah should be able too

yes, edit icon and background...

And on my test, i have 2 game that not working : 

- Phineas and Ferb Across the 2nd Dimension[UCES-01564]
- SSX On Tour ULES00192

both freeze on loading screen...

**Comment by LiEnby** [comment]
I was able to get in game on SSX On Tour.. Theres some broken collision detection but not sure.

But yes the phineas and ferb game crashes in the loading screen. Same crash occurs in adrenaline and also using chovy-sign .. This really does look like a pspemu issue but umm i cant find the game on PS Store to check the offical release. must have been delisted or possibly was never sold for the vita to begin with ..
