### ISSUE TITLE
Game language

### ISSUE THREAD

**Issue by EllenZhao** [LiEnby/NoPspEmuDrm#7]
can't change game language by system language

**Comment by LiEnby** [comment]
I highly doubt this would be an issue w nopspemudrm ..

**Comment by EllenZhao** [comment]
Final Fantasy III, I changed system language to Chinese, but it still display english. It worked on adrenaline

**Comment by EllenZhao** [comment]
I guess the language config was not loaded when lauching PSPEMU

**Comment by EllenZhao** [comment]
Sorry, the download on PKGJ does not support Chinese. The previously downloaded ISO file supports Chinese

**Comment by EllenZhao** [comment]
not a issue
