### ISSUE TITLE
Persona 2: Eternal Punishment fan translation gets a bubble but fails to launch

### ISSUE THREAD

**Issue by SimonAfek** [LiEnby/NoPspEmuDrm#8]
I have the fan translation of Persona 2: Eternal Punishment PSP installed on my Vita (NPJH50581, link to fan translation [here](https://github.com/sayucchin/P2-EP-PSP/)). Your VitaShell fork gives it a bubble when refreshing the LiveArea, but unfortunately it fails to start and just gives an error message.

**Comment by LiEnby** [comment]
there patching the EBOOT.BIN so its probably being replaced with an unsigned version,

**Comment by SimonAfek** [comment]
Yeah, I was wondering if there's a way to detect that so it doesn't get a bubble?

**Comment by SimonAfek** [comment]
Fair enough, I'll just remove the bubble from my app.db. Thanks for this tool by the way - it's great :)

**Comment by 0ver-flow** [comment]
You can always extract the EBOOT.BIN using UMDGen, sign it using sign_np, rebuild the ISO with UMDGen (follow the first 3 steps of [this guide](https://forum.devchroma.nl/index.php?topic=12.0)), from there you can either use ChovySign or sign_np to sign and encrypt the ISO to EBOOT.PBP. After that's done, drag to ux0:pspemu/PSP/GAME/<SERIAL> and refresh LiveArea using LiEnby's VitaShell fork. Tested with both sign_np and ChovySign, both methods work.

**Comment by caleb39411** [comment]
> You can always extract the EBOOT.BIN using UMDGen, sign it using sign_np, rebuild the ISO with UMDGen (follow the first 3 steps of [this guide](https://forum.devchroma.nl/index.php?topic=12.0)), from there you can ~either~ use ChovySign ~or sign_np~ to sign and encrypt the ISO to EBOOT.PBP. After that's done, drag to ux0:pspemu/PSP/GAME/ and refresh LiveArea using LiEnby's VitaShell fork. Tested with ~both sign_np and~ ChovySign ~, both methods work.~ (sign_np seems to crash and throw an error, despite working the first time)

I tried this with an English patch of Hatsune Miku Project Diva, and on the last step, neither would produce a usable EBOOT.PBP (in both PPSSPP and pspemu) unless I applied compression, where both chovysign and sign_np worked fine.

**Comment by 0ver-flow** [comment]
Thanks, I am using Digimon Adventure [NPJH50686] with an English
translation. I used compression with sign_np and not ChovySign. Going to
try without compression now.

**Comment by 0ver-flow** [comment]
With or without compression, sign_np's product managed to boot and play
just fine in PPSSPP. However, with sign_np and NoPspDrmEmu, it crashes with
the same error in the same place.
