### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by Jordan95c** [LiEnby/NoPspEmuDrm#9]
Bonjour, je me demande si l'on peut réaliser cela avec carte mémoire Sony montée en uma0??lorsque je change moi même la partition soit pkgj télécharge quand même les jeux PSP sur la sd2vita en Ux0 ,soit il télécharge bien comme je veux uma0 mais les jeux PSP ne sont plus sur livearea et obliger de passer par adrénaline....
Je souhaite télécharger mes jeux PSP sur uma0 et les voir et les lire depuis livearea sans adrénaline ...et télécharger les jeux psvita sur Ux0 sd2vita...est ce possible d'avoir le tout ...merci par avance pour votre retour...et merci pour tout good job déjà effectué merci beaucoup à vous.

**Comment by Jordan95c** [comment]
J'ai oublié je suis sous henkaku enso 3.65 
Sd2vita 128go memeory cars Sony 14go
Pkgj beta v056 fork vitashell ok

**Comment by LiEnby** [comment]
ScePromoterUtil copy games to ux0:/pspemu on install, they are then registered into app.db with path like "ux0:/pspemu/PSP/GAME/SCUS10000/EBOOT.PBP" 

as well as that the ms0: fios overlay will always be overlay of ux0:/pspemu . . . 

there would be alot of places to patch the "ux0:pspemu" to accomplish this is what im getting at-
anyway i think the easiest way to do what your asking is probably to create a fios2 overlay of ux0:/pspemu to uma0:/pspemu ... 

maybe like a generic fios2 plugin to overlay anything to anything else, could be useful

But as this is promoter related its kind of out of scope for NoPspEmuDrm ..
